/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFAZ;

import javax.swing.JOptionPane;

/**
 *
 * @author chuy4
 */
public class MostrarE extends javax.swing.JFrame {
    private String varCadena;
    private String valCadena;
    private String varResultado;
    private String valResultado;
    private String varFigura;
    private String valFigura;
    private String varColor;
    private String valColor;
    /**
     * Creates new form MostrarE
     */
    public MostrarE() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Mostrar (Entero) - M4TH3C");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel130 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Cadena = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Color = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Figura = new javax.swing.JTextArea();
        jPanel12 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        E = new javax.swing.JTextField();
        D6 = new javax.swing.JTextField();
        D5 = new javax.swing.JTextField();
        D4 = new javax.swing.JTextField();
        D3 = new javax.swing.JTextField();
        D2 = new javax.swing.JTextField();
        D1 = new javax.swing.JTextField();
        F16 = new javax.swing.JPanel();
        F15 = new javax.swing.JPanel();
        F14 = new javax.swing.JPanel();
        F13 = new javax.swing.JPanel();
        F12 = new javax.swing.JPanel();
        F11 = new javax.swing.JPanel();
        btnDibujar = new javax.swing.JButton();

        jPanel130.setBackground(new java.awt.Color(155, 170, 196));

        javax.swing.GroupLayout jPanel130Layout = new javax.swing.GroupLayout(jPanel130);
        jPanel130.setLayout(jPanel130Layout);
        jPanel130Layout.setHorizontalGroup(
            jPanel130Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel130Layout.setVerticalGroup(
            jPanel130Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mostrar (Entero)");

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jPanel2.setBackground(new java.awt.Color(153, 51, 255));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("INTERFAZ GENERADA POR LA FUNCIÓN DE MOSTRAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(153, 51, 255));

        jPanel9.setBackground(new java.awt.Color(0, 0, 153));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("CADENA");

        Cadena.setEditable(false);
        Cadena.setBackground(new java.awt.Color(255, 255, 255));
        Cadena.setColumns(20);
        Cadena.setRows(4);
        jScrollPane3.setViewportView(Cadena);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(0, 0, 153));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("COLOR");

        Color.setEditable(false);
        Color.setBackground(new java.awt.Color(255, 255, 255));
        Color.setColumns(20);
        Color.setRows(4);
        jScrollPane2.setViewportView(Color);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(0, 0, 153));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("FIGURA");

        Figura.setEditable(false);
        Figura.setBackground(new java.awt.Color(255, 255, 255));
        Figura.setColumns(20);
        Figura.setRows(4);
        Figura.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(Figura);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(153, 51, 255));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("RESULTADO");

        E.setEditable(false);
        E.setBackground(new java.awt.Color(255, 255, 255));

        D6.setEditable(false);
        D6.setBackground(new java.awt.Color(255, 255, 255));

        D5.setEditable(false);
        D5.setBackground(new java.awt.Color(255, 255, 255));

        D4.setEditable(false);
        D4.setBackground(new java.awt.Color(255, 255, 255));

        D3.setEditable(false);
        D3.setBackground(new java.awt.Color(255, 255, 255));

        D2.setEditable(false);
        D2.setBackground(new java.awt.Color(255, 255, 255));

        D1.setEditable(false);
        D1.setBackground(new java.awt.Color(255, 255, 255));

        F16.setBackground(new java.awt.Color(155, 170, 196));

        javax.swing.GroupLayout F16Layout = new javax.swing.GroupLayout(F16);
        F16.setLayout(F16Layout);
        F16Layout.setHorizontalGroup(
            F16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        F16Layout.setVerticalGroup(
            F16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        F15.setBackground(new java.awt.Color(155, 170, 196));

        javax.swing.GroupLayout F15Layout = new javax.swing.GroupLayout(F15);
        F15.setLayout(F15Layout);
        F15Layout.setHorizontalGroup(
            F15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        F15Layout.setVerticalGroup(
            F15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        F14.setBackground(new java.awt.Color(155, 170, 196));

        javax.swing.GroupLayout F14Layout = new javax.swing.GroupLayout(F14);
        F14.setLayout(F14Layout);
        F14Layout.setHorizontalGroup(
            F14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        F14Layout.setVerticalGroup(
            F14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        F13.setBackground(new java.awt.Color(155, 170, 196));

        javax.swing.GroupLayout F13Layout = new javax.swing.GroupLayout(F13);
        F13.setLayout(F13Layout);
        F13Layout.setHorizontalGroup(
            F13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        F13Layout.setVerticalGroup(
            F13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        F12.setBackground(new java.awt.Color(155, 170, 196));

        javax.swing.GroupLayout F12Layout = new javax.swing.GroupLayout(F12);
        F12.setLayout(F12Layout);
        F12Layout.setHorizontalGroup(
            F12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        F12Layout.setVerticalGroup(
            F12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        F11.setBackground(new java.awt.Color(155, 170, 196));

        javax.swing.GroupLayout F11Layout = new javax.swing.GroupLayout(F11);
        F11.setLayout(F11Layout);
        F11Layout.setHorizontalGroup(
            F11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        F11Layout.setVerticalGroup(
            F11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnDibujar.setText("Dibujar");
        btnDibujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDibujarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(E, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(btnDibujar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addComponent(F16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(F15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addComponent(D6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(D5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(D1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(F11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(D4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(D6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(D3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(D2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(D1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(D5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(F12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(F13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(F16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(F15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(F14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(F11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(btnDibujar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDibujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDibujarActionPerformed
        if(valFigura.equals("Cuadrado")){
            int y1 = 5;
            int y2 = 55;
            for(int i = 0; i < Integer.parseInt(D1.getText());i++){
                Dibujar.Cuadrado(F11.getGraphics(),valColor,y1,y2);
                y1 += 55;
                y2 += 55;
            }
            y1 = 5;
            y2 = 55;
            for(int i = 0; i < Integer.parseInt(D2.getText());i++){
                Dibujar.Cuadrado(F12.getGraphics(),valColor,y1,y2);
                y1 += 55;
                y2 += 55;
            }
            y1 = 5;
            y2 = 55;
            for(int i = 0; i < Integer.parseInt(D3.getText());i++){
                Dibujar.Cuadrado(F13.getGraphics(),valColor,y1,y2);
                y1 += 55;
                y2 += 55;
            }
            y1 = 5;
            y2 = 55;
            for(int i = 0; i < Integer.parseInt(D4.getText());i++){
                Dibujar.Cuadrado(F14.getGraphics(),valColor,y1,y2);
                y1 += 55;
                y2 += 55;
            }
            y1 = 5;
            y2 = 55;
            for(int i = 0; i < Integer.parseInt(D5.getText());i++){
                Dibujar.Cuadrado(F15.getGraphics(),valColor,y1,y2);
                y1 += 55;
                y2 += 55;
            }
            y1 = 5;
            y2 = 55;
            for(int i = 0; i < Integer.parseInt(D6.getText());i++){
                Dibujar.Cuadrado(F16.getGraphics(),valColor,y1,y2);
                y1 += 55;
                y2 += 55;
            }
        }else if(valFigura.equals("Triangulo")){
            int y1 = 5;
            int y2 = 55;
            for(int i = 0; i < Integer.parseInt(D1.getText());i++){
                Dibujar.Triangulo(F11.getGraphics(),valColor,y1,y2);
                y1 += 55;
                y2 += 55;
            }
            y1 = 5;
            y2 = 55;
            for(int i = 0; i < Integer.parseInt(D2.getText());i++){
                Dibujar.Triangulo(F12.getGraphics(),valColor,y1,y2);
                y1 += 55;
                y2 += 55;
            }
            y1 = 5;
            y2 = 55;
            for(int i = 0; i < Integer.parseInt(D3.getText());i++){
                Dibujar.Triangulo(F13.getGraphics(),valColor,y1,y2);
                y1 += 55;
                y2 += 55;
            }
            y1 = 5;
            y2 = 55;
            for(int i = 0; i < Integer.parseInt(D4.getText());i++){
                Dibujar.Triangulo(F14.getGraphics(),valColor,y1,y2);
                y1 += 55;
                y2 += 55;
            }
            y1 = 5;
            y2 = 55;
            for(int i = 0; i < Integer.parseInt(D5.getText());i++){
                Dibujar.Triangulo(F15.getGraphics(),valColor,y1,y2);
                y1 += 55;
                y2 += 55;
            }
            y1 = 5;
            y2 = 55;
            for(int i = 0; i < Integer.parseInt(D6.getText());i++){
                Dibujar.Triangulo(F16.getGraphics(),valColor,y1,y2);
                y1 += 55;
                y2 += 55;
            }
        }else if(valFigura.equals("Rectangulo")){
            int y1 = 15;
            int y2 = 45;
            for(int i = 0; i < Integer.parseInt(D1.getText());i++){
                Dibujar.Rectangulo(F11.getGraphics(),valColor,y1,y2);
                y1 += 55;
                y2 += 55;
            }
            y1 = 15;
            y2 = 45;
            for(int i = 0; i < Integer.parseInt(D2.getText());i++){
                Dibujar.Rectangulo(F12.getGraphics(),valColor,y1,y2);
                y1 += 55;
                y2 += 55;
            }
            y1 = 15;
            y2 = 45;
            for(int i = 0; i < Integer.parseInt(D3.getText());i++){
                Dibujar.Rectangulo(F13.getGraphics(),valColor,y1,y2);
                y1 += 55;
                y2 += 55;
            }
            y1 = 15;
            y2 = 45;
            for(int i = 0; i < Integer.parseInt(D4.getText());i++){
                Dibujar.Rectangulo(F14.getGraphics(),valColor,y1,y2);
                y1 += 55;
                y2 += 55;
            }
            y1 = 15;
            y2 = 45;
            for(int i = 0; i < Integer.parseInt(D5.getText());i++){
                Dibujar.Rectangulo(F15.getGraphics(),valColor,y1,y2);
                y1 += 55;
                y2 += 55;
            }
            y1 = 15;
            y2 = 45;
            for(int i = 0; i < Integer.parseInt(D6.getText());i++){
                Dibujar.Rectangulo(F16.getGraphics(),valColor,y1,y2);
                y1 += 55;
                y2 += 55;
            }
        }else if(valFigura.equals("Rombo")){
            int y1 = 5;
            int y2 = 30;
            int y3 = 55;
            for(int i = 0; i < Integer.parseInt(D1.getText());i++){
                Dibujar.Rombo(F11.getGraphics(),valColor,y1,y2,y3);
                y1 += 55;
                y2 += 55;
                y3 += 55;
            }
            y1 = 5;
            y2 = 30;
            y3 = 55;
            for(int i = 0; i < Integer.parseInt(D2.getText());i++){
                Dibujar.Rombo(F12.getGraphics(),valColor,y1,y2,y3);
                y1 += 55;
                y2 += 55;
                y3 += 55;
            }
            y1 = 5;
            y2 = 30;
            y3 = 55;
            for(int i = 0; i < Integer.parseInt(D3.getText());i++){
                Dibujar.Rombo(F13.getGraphics(),valColor,y1,y2,y3);
                y1 += 55;
                y2 += 55;
                y3 += 55;
            }
            y1 = 5;
            y2 = 30;
            y3 = 55;
            for(int i = 0; i < Integer.parseInt(D4.getText());i++){
                Dibujar.Rombo(F14.getGraphics(),valColor,y1,y2,y3);
                y1 += 55;
                y2 += 55;
                y3 += 55;
            }
            y1 = 5;
            y2 = 30;
            y3 = 55;
            for(int i = 0; i < Integer.parseInt(D5.getText());i++){
                Dibujar.Rombo(F15.getGraphics(),valColor,y1,y2,y3);
                y1 += 55;
                y2 += 55;
                y3 += 55;
            }
            y1 = 5;
            y2 = 30;
            y3 = 55;
            for(int i = 0; i < Integer.parseInt(D6.getText());i++){
                Dibujar.Rombo(F16.getGraphics(),valColor,y1,y2,y3);
                y1 += 55;
                y2 += 55;
                y3 += 55;
            }
        }else if(valFigura.equals("Circulo")){
            int y1 = 5;
            for(int i = 0; i < Integer.parseInt(D1.getText());i++){
                Dibujar.Circulo(F11.getGraphics(),valColor,y1);
                y1 += 55;
            }
            y1 = 5;
            for(int i = 0; i < Integer.parseInt(D2.getText());i++){
                Dibujar.Circulo(F12.getGraphics(),valColor,y1);
                y1 += 55;
            }
            y1 = 5;
            for(int i = 0; i < Integer.parseInt(D3.getText());i++){
                Dibujar.Circulo(F13.getGraphics(),valColor,y1);
                y1 += 55;
            }
            y1 = 5;
            for(int i = 0; i < Integer.parseInt(D4.getText());i++){
                Dibujar.Circulo(F14.getGraphics(),valColor,y1);
                y1 += 55;
            }
            y1 = 5;
            for(int i = 0; i < Integer.parseInt(D5.getText());i++){
                Dibujar.Circulo(F15.getGraphics(),valColor,y1);
                y1 += 55;
            }
            y1 = 5;
            for(int i = 0; i < Integer.parseInt(D6.getText());i++){
                Dibujar.Circulo(F16.getGraphics(),valColor,y1);
                y1 += 55;
            }
        }
    }//GEN-LAST:event_btnDibujarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarE().setVisible(true);
            }
        });
    }
    //CADENA
    public void setCadena(String varc,String valc){
        this.varCadena = varc;
        this.valCadena = valc;
    }
    public void Cadena(){
        Cadena.append("---> Variable: "+varCadena+"\n\n--->Valor: "+valCadena);
    }
    //CADENA
    //RESULTADO
    public void setResultado(String varr,String valr){
        this.varResultado = varr;
        this.valResultado = valr;
    }
    public void Resultado(){
        if(valResultado.contains("-")){
            if(valResultado.chars().count() == 7){
                E.setText(Character.toString(valResultado.charAt(0)));
                D6.setText(Character.toString(valResultado.charAt(1)));
                D5.setText(Character.toString(valResultado.charAt(2)));
                D4.setText(Character.toString(valResultado.charAt(3)));
                D4.setText(Character.toString(valResultado.charAt(4)));
                D2.setText(Character.toString(valResultado.charAt(5)));
                D1.setText(Character.toString(valResultado.charAt(6)));
            }else if(valResultado.chars().count() == 6){
                E.setText(Character.toString(valResultado.charAt(0)));
                D5.setText(Character.toString(valResultado.charAt(1)));
                D4.setText(Character.toString(valResultado.charAt(2)));
                D3.setText(Character.toString(valResultado.charAt(3)));
                D2.setText(Character.toString(valResultado.charAt(4)));
                D1.setText(Character.toString(valResultado.charAt(5)));
            }else if(valResultado.chars().count() == 5){
                E.setText(Character.toString(valResultado.charAt(0)));
                D4.setText(Character.toString(valResultado.charAt(1)));
                D3.setText(Character.toString(valResultado.charAt(2)));
                D2.setText(Character.toString(valResultado.charAt(3)));
                D1.setText(Character.toString(valResultado.charAt(4)));
            }else if(valResultado.chars().count() == 4){
                E.setText(Character.toString(valResultado.charAt(0)));
                D3.setText(Character.toString(valResultado.charAt(1)));
                D2.setText(Character.toString(valResultado.charAt(2)));
                D1.setText(Character.toString(valResultado.charAt(3)));
            }else if(valResultado.chars().count() == 3){
                E.setText(Character.toString(valResultado.charAt(0)));
                D2.setText(Character.toString(valResultado.charAt(1)));
                D1.setText(Character.toString(valResultado.charAt(2)));
            }else if(valResultado.chars().count() == 2){
                E.setText(Character.toString(valResultado.charAt(0)));
                D1.setText(Character.toString(valResultado.charAt(1)));
            }
        }else{
            if(valResultado.chars().count() == 6){
                E.setText("+");
                D6.setText(Character.toString(valResultado.charAt(0)));
                D5.setText(Character.toString(valResultado.charAt(1)));
                D4.setText(Character.toString(valResultado.charAt(2)));
                D4.setText(Character.toString(valResultado.charAt(3)));
                D2.setText(Character.toString(valResultado.charAt(4)));
                D1.setText(Character.toString(valResultado.charAt(5)));
            }else if(valResultado.chars().count() == 5){
                E.setText("+");
                D5.setText(Character.toString(valResultado.charAt(0)));
                D4.setText(Character.toString(valResultado.charAt(1)));
                D3.setText(Character.toString(valResultado.charAt(2)));
                D2.setText(Character.toString(valResultado.charAt(3)));
                D1.setText(Character.toString(valResultado.charAt(4)));
            }else if(valResultado.chars().count() == 4){
                E.setText("+");
                D4.setText(Character.toString(valResultado.charAt(0)));
                D3.setText(Character.toString(valResultado.charAt(1)));
                D2.setText(Character.toString(valResultado.charAt(2)));
                D1.setText(Character.toString(valResultado.charAt(3)));
            }else if(valResultado.chars().count() == 3){
                E.setText("+");
                D3.setText(Character.toString(valResultado.charAt(0)));
                D2.setText(Character.toString(valResultado.charAt(1)));
                D1.setText(Character.toString(valResultado.charAt(2)));
            }else if(valResultado.chars().count() == 2){
                E.setText("+");
                D2.setText(Character.toString(valResultado.charAt(0)));
                D1.setText(Character.toString(valResultado.charAt(1)));
            }else if(valResultado.chars().count() == 1){
                E.setText("+");
                D1.setText(Character.toString(valResultado.charAt(0)));
            }
        }

    }
    //RESULTADO
    //FIGURA
    public void setFigura(String varf,String valf){
        this.varFigura = varf;
        this.valFigura = valf;
    }
    public void Figura(){
        Figura.append("---> Variable: "+varFigura+"\n\n---> Valor: "+valFigura);
    }
    //FIGURA
    //COLOR
    public void setColor(String varc,String valc){
        this.varColor = varc;
        this.valColor = valc;
    }
    public void Color(){
        Color.append("---> Variable: "+varColor+"\n\n---> Valor: "+valColor);
    }
    //COLOR

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Cadena;
    private javax.swing.JTextArea Color;
    private javax.swing.JTextField D1;
    private javax.swing.JTextField D2;
    private javax.swing.JTextField D3;
    private javax.swing.JTextField D4;
    private javax.swing.JTextField D5;
    private javax.swing.JTextField D6;
    private javax.swing.JTextField E;
    private javax.swing.JPanel F11;
    private javax.swing.JPanel F12;
    private javax.swing.JPanel F13;
    private javax.swing.JPanel F14;
    private javax.swing.JPanel F15;
    private javax.swing.JPanel F16;
    private javax.swing.JTextArea Figura;
    private javax.swing.JButton btnDibujar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel130;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
